import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { Pool } from "pg";

export type Session = { role: "SUPER_ADMIN" | "TEACHER"; username: string; displayName: string; createdAt: number };
const HEARTBEAT_MAX_GAP_SECONDS = 90;
const SUPER_ADMIN_USERNAME = process.env.SUPER_ADMIN_USERNAME || "admin";
const SUPER_ADMIN_PASSWORD = process.env.SUPER_ADMIN_PASSWORD || "admin@123456";
const GOOGLE_APPS_SCRIPT_URL = process.env.GOOGLE_APPS_SCRIPT_URL || "";
let pool: Pool | null = null; let dbReady: Promise<void> | null = null;
function getPool(){ if(!process.env.DATABASE_URL) return null; if(!pool) pool=new Pool({connectionString:process.env.DATABASE_URL,max:3,idleTimeoutMillis:10000,connectionTimeoutMillis:10000,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined}); return pool; }
async function initDatabase(){ const db=getPool(); if(!db)return; await db.query(`
CREATE TABLE IF NOT EXISTS app_teachers(username TEXT PRIMARY KEY,password TEXT NOT NULL,display_name TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_classes(id TEXT PRIMARY KEY,name TEXT NOT NULL,class_code TEXT NOT NULL,school_year TEXT NOT NULL DEFAULT '',grade INTEGER NOT NULL DEFAULT 6,teacher_username TEXT NOT NULL,teacher_name TEXT NOT NULL,students JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_submissions(attempt_id TEXT PRIMARY KEY,payload JSONB NOT NULL,recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_presence(session_id TEXT PRIMARY KEY,payload JSONB NOT NULL,last_seen_ms BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS app_sessions(token TEXT PRIMARY KEY,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_lessons(id TEXT PRIMARY KEY,grade INTEGER NOT NULL DEFAULT 6,teacher_username TEXT NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_questions(id TEXT PRIMARY KEY,grade INTEGER NOT NULL DEFAULT 6,teacher_username TEXT NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_exams(id TEXT PRIMARY KEY,grade INTEGER NOT NULL DEFAULT 6,teacher_username TEXT NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_formulas(id TEXT PRIMARY KEY,grade INTEGER NOT NULL DEFAULT 6,teacher_username TEXT NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_progress(id TEXT PRIMARY KEY,student_id TEXT NOT NULL,lesson_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'NOT_STARTED',payload JSONB NOT NULL DEFAULT '{}'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE app_classes ADD COLUMN IF NOT EXISTS grade INTEGER NOT NULL DEFAULT 6;
CREATE INDEX IF NOT EXISTS app_submissions_payload_gin ON app_submissions USING GIN(payload);
CREATE INDEX IF NOT EXISTS app_classes_teacher_idx ON app_classes(teacher_username);
CREATE INDEX IF NOT EXISTS app_presence_last_seen_idx ON app_presence(last_seen_ms);
`); }
async function ensureDatabase(){ if(!getPool())return; if(!dbReady) dbReady=initDatabase().catch(err=>{dbReady=null;throw err;}); await dbReady; }
async function query<T=any>(text:string,values:any[]=[]){ await ensureDatabase(); const db=getPool(); if(!db)throw new Error("DATABASE_URL chưa được cấu hình."); return db.query(text,values); }
function slugifyClass(value:string){return value.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,"-").replace(/-+/g,"-");}
function memoryFallback(){return !getPool();}
function normalizeGrade(v:any){const g=Number(v||6);return Number.isInteger(g)&&g>=6&&g<=12?g:6;}
async function syncSubmissionToGoogle(recorded:any){
  if(!GOOGLE_APPS_SCRIPT_URL) return {enabled:false,ok:false};
  try {
    const response=await fetch(GOOGLE_APPS_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submission",...recorded}),signal:AbortSignal.timeout(8000)});
    return {enabled:true,ok:response.ok};
  } catch { return {enabled:true,ok:false}; }
}

export async function createApp(){
 const app=express(); app.use(express.json({limit:"10mb"}));
 const memory={submissions:[] as any[],presence:new Map<string,any>(),sessions:new Map<string,Session>(),classes:new Map<string,any>(),teachers:new Map<string,{username:string;password:string;displayName:string;active:boolean;createdAt:string}>()};
 async function getSession(req:express.Request):Promise<(Session&{token:string})|null>{const header=req.headers.authorization||"";const token=header.startsWith("Bearer ")?header.slice(7):"";if(!token)return null;if(memoryFallback()){const session=memory.sessions.get(token);return session?{token,...session}:null;}const result=await query<{payload:Session}>("SELECT payload FROM app_sessions WHERE token=$1",[token]);const session=result.rows[0]?.payload;return session?{token,...session}:null;}
 async function requireRole(req:express.Request,res:express.Response,roles:Session["role"][]){const session=await getSession(req);if(!session){res.status(401).json({success:false,message:"Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại."});return null;}if(!roles.includes(session.role)){res.status(403).json({success:false,message:"Bạn không có quyền thực hiện thao tác này."});return null;}return session;}
 const requireAdmin=(req:express.Request,res:express.Response)=>requireRole(req,res,["SUPER_ADMIN"]); const requireTeacher=(req:express.Request,res:express.Response)=>requireRole(req,res,["TEACHER"]);
 app.get("/api/health",async(_req,res)=>{try{await ensureDatabase();if(memoryFallback())return res.json({status:"ok",database:"memory",googleSheets:Boolean(GOOGLE_APPS_SCRIPT_URL),time:new Date().toISOString()});await query("SELECT 1");res.json({status:"ok",database:"postgres",googleSheets:Boolean(GOOGLE_APPS_SCRIPT_URL),time:new Date().toISOString()});}catch(err:any){res.status(500).json({status:"error",database:"postgres",message:err.message});}});
 app.post("/api/auth/login",async(req,res)=>{try{const cleanUsername=String(req.body?.username||"").trim();const cleanPassword=String(req.body?.password||"");let session:Session|null=null;if(cleanUsername===SUPER_ADMIN_USERNAME&&cleanPassword===SUPER_ADMIN_PASSWORD)session={role:"SUPER_ADMIN",username:SUPER_ADMIN_USERNAME,displayName:"Quản trị viên",createdAt:Date.now()};else if(memoryFallback()){const teacher=memory.teachers.get(cleanUsername);if(teacher?.active&&teacher.password===cleanPassword)session={role:"TEACHER",username:teacher.username,displayName:teacher.displayName,createdAt:Date.now()};}else{const result=await query<{username:string;display_name:string;active:boolean;password:string}>("SELECT username,display_name,active,password FROM app_teachers WHERE username=$1",[cleanUsername]);const teacher=result.rows[0];if(teacher?.active&&teacher.password===cleanPassword)session={role:"TEACHER",username:teacher.username,displayName:teacher.display_name,createdAt:Date.now()};}if(!session)return res.status(401).json({success:false,message:"Tài khoản hoặc mật khẩu không đúng, hoặc tài khoản đã bị khóa."});const token=`sess_${Date.now()}_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}`;if(memoryFallback())memory.sessions.set(token,session);else await query("INSERT INTO app_sessions(token,payload) VALUES($1,$2::jsonb)",[token,JSON.stringify(session)]);res.json({success:true,session:{token,...session}});}catch(err:any){res.status(500).json({success:false,message:err.message||"Lỗi máy chủ."});}});
 app.post("/api/auth/logout",async(req,res)=>{try{const header=req.headers.authorization||"";const token=header.startsWith("Bearer ")?header.slice(7):"";if(token){if(memoryFallback())memory.sessions.delete(token);else await query("DELETE FROM app_sessions WHERE token=$1",[token]);}res.json({success:true});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.get("/api/teachers",async(req,res)=>{try{if(!(await requireAdmin(req,res)))return;if(memoryFallback())return res.json({success:true,data:Array.from(memory.teachers.values()).map(({password,...t})=>t)});const r=await query("SELECT username,display_name AS \"displayName\",active,created_at AS \"createdAt\" FROM app_teachers ORDER BY created_at DESC");res.json({success:true,data:r.rows});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.post("/api/teachers",async(req,res)=>{try{if(!(await requireAdmin(req,res)))return;const username=String(req.body?.username||"").trim();const password=String(req.body?.password||"");const displayName=String(req.body?.displayName||"").trim();if(!username||!password||!displayName)return res.status(400).json({success:false,message:"Cần tài khoản, mật khẩu và tên giáo viên."});if(username===SUPER_ADMIN_USERNAME)return res.status(409).json({success:false,message:"Tài khoản đã tồn tại."});if(memoryFallback()){if(memory.teachers.has(username))return res.status(409).json({success:false,message:"Tài khoản đã tồn tại."});memory.teachers.set(username,{username,password,displayName,active:true,createdAt:new Date().toISOString()});}else{const r=await query("INSERT INTO app_teachers(username,password,display_name,active) VALUES($1,$2,$3,true) ON CONFLICT(username) DO NOTHING RETURNING username",[username,password,displayName]);if(!r.rowCount)return res.status(409).json({success:false,message:"Tài khoản đã tồn tại."});}res.json({success:true,data:{username,displayName,active:true}});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.patch("/api/teachers/:username",async(req,res)=>{try{if(!(await requireAdmin(req,res)))return;const username=req.params.username;if(memoryFallback()){const teacher=memory.teachers.get(username);if(!teacher)return res.status(404).json({success:false,message:"Không tìm thấy giáo viên."});if(typeof req.body?.active==="boolean")teacher.active=req.body.active;if(typeof req.body?.password==="string"&&req.body.password)teacher.password=req.body.password;if(typeof req.body?.displayName==="string"&&req.body.displayName.trim())teacher.displayName=req.body.displayName.trim();memory.teachers.set(username,teacher);return res.json({success:true,data:{username,displayName:teacher.displayName,active:teacher.active}});}const current=await query<{display_name:string;active:boolean}>("SELECT display_name,active FROM app_teachers WHERE username=$1",[username]);if(!current.rowCount)return res.status(404).json({success:false,message:"Không tìm thấy giáo viên."});const displayName=typeof req.body?.displayName==="string"&&req.body.displayName.trim()?req.body.displayName.trim():current.rows[0].display_name;const active=typeof req.body?.active==="boolean"?req.body.active:current.rows[0].active;const password=typeof req.body?.password==="string"&&req.body.password?req.body.password:undefined;if(password)await query("UPDATE app_teachers SET display_name=$2,active=$3,password=$4 WHERE username=$1",[username,displayName,active,password]);else await query("UPDATE app_teachers SET display_name=$2,active=$3 WHERE username=$1",[username,displayName,active]);res.json({success:true,data:{username,displayName,active}});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.post("/api/classes",async(req,res)=>{try{const auth=await requireTeacher(req,res);if(!auth)return;const cleanName=String(req.body?.name||"").trim();const grade=normalizeGrade(req.body?.grade);if(!cleanName)return res.status(400).json({success:false,message:"Vui lòng nhập tên lớp."});const id=`class_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;const classCode=`${slugifyClass(cleanName)}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const schoolYear=String(req.body?.schoolYear||"");const record={id,name:cleanName,classCode,schoolYear,grade,teacherUsername:auth.username,teacherName:auth.displayName,createdAt:new Date().toISOString(),students:[] as any[]};if(memoryFallback())memory.classes.set(id,record);else await query("INSERT INTO app_classes(id,name,class_code,school_year,grade,teacher_username,teacher_name,students) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)",[id,cleanName,classCode,schoolYear,grade,auth.username,auth.displayName,"[]"]);res.json({success:true,data:record,joinUrl:`/?class=${encodeURIComponent(id)}`});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 async function getClass(id:string){if(memoryFallback())return memory.classes.get(id)||null;const r=await query<any>("SELECT id,name,class_code AS \"classCode\",school_year AS \"schoolYear\",grade,teacher_username AS \"teacherUsername\",teacher_name AS \"teacherName\",students,created_at AS \"createdAt\" FROM app_classes WHERE id=$1",[id]);return r.rows[0]||null;}
 app.get("/api/classes",async(req,res)=>{try{const auth=await requireTeacher(req,res);if(!auth)return;if(memoryFallback())return res.json({success:true,data:Array.from(memory.classes.values()).filter(c=>c.teacherUsername===auth.username).map(({students,...c})=>({...c,studentCount:students.length}))});const r=await query<any>("SELECT id,name,class_code AS \"classCode\",school_year AS \"schoolYear\",grade,teacher_username AS \"teacherUsername\",teacher_name AS \"teacherName\",created_at AS \"createdAt\",jsonb_array_length(students) AS \"studentCount\" FROM app_classes WHERE teacher_username=$1 ORDER BY created_at DESC",[auth.username]);res.json({success:true,data:r.rows});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.get("/api/classes/:id",async(req,res)=>{try{const record=await getClass(req.params.id);if(!record)return res.status(404).json({success:false,message:"Không tìm thấy lớp."});res.json({success:true,data:{id:record.id,name:record.name,classCode:record.classCode,schoolYear:record.schoolYear,grade:Number(record.grade||6),teacherName:record.teacherName}});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.post("/api/students/login",async(req,res)=>{try{const classId=String(req.body?.classId||"");const cleanName=String(req.body?.studentName||"").trim();const dob=String(req.body?.dateOfBirth||"").trim();const record=await getClass(classId);if(!record||!cleanName||!dob)return res.status(400).json({success:false,message:"Thiếu thông tin học sinh hoặc lớp."});const students=Array.isArray(record.students)?record.students:[];let student=students.find((s:any)=>String(s.studentName).toLowerCase()===cleanName.toLowerCase()&&s.dateOfBirth===dob);if(!student){student={id:`stu_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,studentName:cleanName,dateOfBirth:dob,createdAt:new Date().toISOString()};students.push(student);if(memoryFallback())memory.classes.set(classId,{...record,students});else await query("UPDATE app_classes SET students=$2::jsonb WHERE id=$1",[classId,JSON.stringify(students)]);}const sessionId=`stu_${Date.now()}_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}`;res.json({success:true,sessionId,studentId:student.id,profile:{studentName:student.studentName,className:record.name,dateOfBirth:student.dateOfBirth,grade:Number(record.grade||6)},classId:record.id,teacherName:record.teacherName,grade:Number(record.grade||6)});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.get("/api/classes/:id/students",async(req,res)=>{try{const auth=await requireTeacher(req,res);if(!auth)return;const record=await getClass(req.params.id);if(!record)return res.status(404).json({success:false,message:"Không tìm thấy lớp."});if(record.teacherUsername!==auth.username)return res.status(403).json({success:false,message:"Bạn không có quyền xem lớp này."});res.json({success:true,data:record.students||[]});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.post("/api/students/heartbeat",async(req,res)=>{try{const{sessionId,studentName,className,dateOfBirth,activity}=req.body||{};if(!sessionId||!studentName||!className||!dateOfBirth)return res.status(400).json({success:false,message:"Thiếu thông tin học sinh."});const now=Date.now();let previous:any=null;if(memoryFallback())previous=memory.presence.get(sessionId);else{const r=await query<{payload:any}>("SELECT payload FROM app_presence WHERE session_id=$1",[sessionId]);previous=r.rows[0]?.payload||null;}const gapSeconds=previous?Math.min(HEARTBEAT_MAX_GAP_SECONDS,Math.max(0,(now-Number(previous.lastSeenMs))/1000)):0;const normalizedActivity=activity==="LEARNING"||activity==="EXAM"?activity:"IDLE";const record=previous||{sessionId,studentName,className,dateOfBirth,onlineSeconds:0,learningSeconds:0,examSeconds:0,examsCompleted:0};record.studentName=studentName;record.className=className;record.dateOfBirth=dateOfBirth;record.onlineSeconds+=gapSeconds;if(normalizedActivity==="LEARNING")record.learningSeconds+=gapSeconds;if(normalizedActivity==="EXAM")record.examSeconds+=gapSeconds;record.lastSeenMs=now;record.lastSeenAt=new Date(now).toISOString();record.lastActivity=normalizedActivity;record.online=true;if(memoryFallback())memory.presence.set(sessionId,record);else await query("INSERT INTO app_presence(session_id,payload,last_seen_ms) VALUES($1,$2::jsonb,$3) ON CONFLICT(session_id) DO UPDATE SET payload=EXCLUDED.payload,last_seen_ms=EXCLUDED.last_seen_ms",[sessionId,JSON.stringify(record),now]);res.json({success:true});}catch(err:any){res.status(500).json({success:false,message:err.message||"Lỗi theo dõi học sinh."});}});
 app.get("/api/students/presence",async(req,res)=>{try{const auth=await requireTeacher(req,res);if(!auth)return;const now=Date.now();let rows:any[]=[];if(memoryFallback())rows=Array.from(memory.presence.values());else{const r=await query<{payload:any}>("SELECT payload FROM app_presence ORDER BY last_seen_ms DESC");rows=r.rows.map(x=>x.payload);}const classes=memoryFallback()?Array.from(memory.classes.values()):(await query<any>("SELECT id,name,teacher_username AS \"teacherUsername\" FROM app_classes")).rows;const data=rows.filter(s=>classes.some((c:any)=>c.name===s.className&&c.teacherUsername===auth.username)).map(s=>({...s,online:now-Number(s.lastSeenMs)<=75000,lastSeenAt:new Date(Number(s.lastSeenMs)).toISOString()}));data.sort((a,b)=>Number(b.online)-Number(a.online)||Number(b.lastSeenMs)-Number(a.lastSeenMs));res.json({success:true,data});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 app.post("/api/submit",async(req,res)=>{try{const submission=req.body;if(!submission.attemptId||!submission.studentName||!submission.className)return res.status(400).json({success:false,message:"Thiếu thông tin bắt buộc."});let existing:any=null;if(memoryFallback())existing=memory.submissions.find(s=>s.attemptId===submission.attemptId);else{const r=await query<{payload:any}>("SELECT payload FROM app_submissions WHERE attempt_id=$1",[submission.attemptId]);existing=r.rows[0]?.payload||null;}if(existing)return res.json({success:true,message:"Lượt làm này đã được ghi nhận trước đó.",data:existing});const recorded={...submission,recordedAt:new Date().toISOString()};if(memoryFallback())memory.submissions.push(recorded);else await query("INSERT INTO app_submissions(attempt_id,payload) VALUES($1,$2::jsonb)",[recorded.attemptId,JSON.stringify(recorded)]);if(recorded.sessionId){if(memoryFallback()){const p=memory.presence.get(recorded.sessionId);if(p){p.examsCompleted=(p.examsCompleted||0)+1;memory.presence.set(recorded.sessionId,p);}}else await query("UPDATE app_presence SET payload=jsonb_set(payload,'{examsCompleted}',to_jsonb(COALESCE((payload->>'examsCompleted')::int,0)+1),true) WHERE session_id=$1",[recorded.sessionId]);}
      const google=await syncSubmissionToGoogle(recorded);
      res.json({success:true,message:"Nộp bài thành công lên hệ thống.",data:recorded,googleSheets:google});
    }catch(err:any){res.status(500).json({success:false,message:err.message||"Lỗi máy chủ."});}});
 app.get("/api/submissions",async(req,res)=>{try{let filtered:any[];if(memoryFallback())filtered=memory.submissions;else filtered=(await query<{payload:any}>("SELECT payload FROM app_submissions ORDER BY recorded_at DESC")).rows.map(x=>x.payload);const{studentName,className,lessonId}=req.query;if(studentName)filtered=filtered.filter(s=>String(s.studentName||"").toLowerCase()===String(studentName).toLowerCase());if(className)filtered=filtered.filter(s=>s.className===className);if(lessonId)filtered=filtered.filter(s=>s.lessonId===lessonId);res.json({success:true,data:filtered});}catch(err:any){res.status(500).json({success:false,message:err.message});}});
 async function contentList(table:string,req:express.Request,res:express.Response){try{const grade=req.query.grade?normalizeGrade(req.query.grade):null;const r=await query<{payload:any;grade:number}>(`SELECT payload,grade FROM ${table} ORDER BY updated_at DESC`);const data=r.rows.filter(x=>!grade||Number(x.grade)===grade).map(x=>({...x.payload,grade:Number(x.grade)}));return res.json({success:true,data});}catch(err:any){return res.status(500).json({success:false,message:err.message});}}
 async function saveContent(table:string,req:express.Request,res:express.Response){try{const auth=await requireRole(req,res,["TEACHER","SUPER_ADMIN"]);if(!auth)return;const id=String(req.body?.id||`${table}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`);const grade=normalizeGrade(req.body?.grade);const payload={...req.body,id,grade};await query(`INSERT INTO ${table}(id,grade,teacher_username,payload,updated_at) VALUES($1,$2,$3,$4::jsonb,NOW()) ON CONFLICT(id) DO UPDATE SET grade=EXCLUDED.grade,payload=EXCLUDED.payload,updated_at=NOW()`,[id,grade,auth.username,JSON.stringify(payload)]);res.json({success:true,data:payload});}catch(err:any){res.status(500).json({success:false,message:err.message});}}
 async function deleteContent(table:string,req:express.Request,res:express.Response){try{const auth=await requireRole(req,res,["TEACHER","SUPER_ADMIN"]);if(!auth)return;await query(`DELETE FROM ${table} WHERE id=$1`,[req.params.id]);res.json({success:true});}catch(err:any){res.status(500).json({success:false,message:err.message});}}
 const registerContent=(name:string,table:string)=>{app.get(`/api/content/${name}`,async(req,res)=>contentList(table,req,res));app.post(`/api/content/${name}`,async(req,res)=>saveContent(table,req,res));app.patch(`/api/content/${name}/:id`,async(req,res)=>saveContent(table,{...req,body:{...req.body,id:req.params.id}} as any,res));app.delete(`/api/content/${name}/:id`,async(req,res)=>deleteContent(table,req,res));};
 registerContent("lessons","app_lessons");registerContent("questions","app_questions");registerContent("exams","app_exams");registerContent("formulas","app_formulas");
 if(process.env.VERCEL)return app;
 if(process.env.NODE_ENV!=="production"){const vite=await createViteServer({server:{middlewareMode:true},appType:"spa"});app.use(vite.middlewares);}else{const distPath=path.join(process.cwd(),"dist");app.use(express.static(distPath));app.get("*",(_req,res)=>res.sendFile(path.join(distPath,"index.html")));}
 return app;
}
if(!process.env.VERCEL){createApp().then(app=>app.listen(Number(process.env.PORT||3000),"0.0.0.0",()=>console.log(`Server running on http://0.0.0.0:${Number(process.env.PORT||3000)}`))).catch(error=>{console.error("Failed to start server:",error);process.exit(1);});}
