import type { VercelRequest, VercelResponse } from "@vercel/node";
import { Pool } from "pg";
// @ts-ignore - server.cjs is generated by the production build.
import { createApp } from "../server.cjs";

let appPromise: Promise<any> | null = null;
let pool: Pool | null = null;

function getPool() {
  if (!process.env.DATABASE_URL) return null;
  if (!pool) pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 3, idleTimeoutMillis: 10000, connectionTimeoutMillis: 10000, ssl: { rejectUnauthorized: false } });
  return pool;
}

async function dbQuery<T = any>(text: string, values: any[] = []) {
  const db = getPool();
  if (!db) throw new Error("DATABASE_URL chưa được cấu hình.");
  return db.query<T>(text, values);
}

function bearer(req: VercelRequest) {
  const raw = String(req.headers.authorization || "");
  return raw.startsWith("Bearer ") ? raw.slice(7).trim() : "";
}

async function getSession(token: string) {
  if (!token) return null;
  const result = await dbQuery<{ payload: any }>("SELECT payload FROM app_sessions WHERE token=$1", [token]);
  const session = result.rows[0]?.payload;
  if (!session) return null;
  if (session.role === "STUDENT" && session.createdAt && Date.now() - Number(session.createdAt) > 1000 * 60 * 60 * 24 * 30) return null;
  return { token, ...session };
}

function contentMatch(pathname: string) {
  const match = pathname.match(/^\/api\/content\/(lessons|questions|exams|formulas)(?:\/([^/]+))?\/?$/);
  return match ? { table: `app_${match[1]}`, id: match[2] ? decodeURIComponent(match[2]) : null } : null;
}

async function handleStudentLogin(req: VercelRequest, res: VercelResponse) {
  const body = req.body && typeof req.body === "object" ? req.body as any : {};
  const classId = String(body.classId || "").trim();
  const cleanName = String(body.studentName || "").trim();
  const dob = String(body.dateOfBirth || "").trim();
  if (!classId || !cleanName || !dob) return res.status(400).json({ success: false, message: "Thiếu thông tin học sinh hoặc lớp." });

  const classResult = await dbQuery<any>("SELECT id,name,class_code AS \"classCode\",school_year AS \"schoolYear\",grade,teacher_username AS \"teacherUsername\",teacher_name AS \"teacherName\",students FROM app_classes WHERE id=$1", [classId]);
  const record = classResult.rows[0];
  if (!record) return res.status(404).json({ success: false, message: "Không tìm thấy lớp." });

  const students = Array.isArray(record.students) ? record.students : [];
  let student = students.find((s: any) => String(s.studentName || "").trim().toLowerCase() === cleanName.toLowerCase() && String(s.dateOfBirth || "") === dob);
  if (!student) {
    student = { id: `stu_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, studentName: cleanName, dateOfBirth: dob, createdAt: new Date().toISOString() };
    students.push(student);
    await dbQuery("UPDATE app_classes SET students=$2::jsonb WHERE id=$1", [classId, JSON.stringify(students)]);
  }

  const sessionId = `stu_${Date.now()}_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}`;
  const sessionPayload = {
    role: "STUDENT",
    studentId: student.id,
    studentName: student.studentName,
    dateOfBirth: student.dateOfBirth,
    classId: record.id,
    className: record.name,
    grade: Number(record.grade || 6),
    teacherUsername: record.teacherUsername,
    teacherName: record.teacherName,
    createdAt: Date.now(),
  };
  await dbQuery("INSERT INTO app_sessions(token,payload) VALUES($1,$2::jsonb)", [sessionId, JSON.stringify(sessionPayload)]);

  return res.json({
    success: true,
    sessionId,
    studentId: student.id,
    profile: { studentName: student.studentName, className: record.name, dateOfBirth: student.dateOfBirth, grade: Number(record.grade || 6) },
    classId: record.id,
    teacherName: record.teacherName,
    grade: Number(record.grade || 6),
  });
}

async function handleContentScope(req: VercelRequest, res: VercelResponse, pathname: string) {
  const info = contentMatch(pathname);
  if (!info) return false;
  const token = bearer(req);
  const session = await getSession(token);
  if (!session) {
    res.status(401).json({ success: false, message: "Bạn cần đăng nhập để truy cập dữ liệu này." });
    return true;
  }

  const method = String(req.method || "GET").toUpperCase();
  const table = info.table;

  if (method === "GET" && !info.id) {
    const query = await dbQuery<any>(`SELECT id,grade,teacher_username AS \"teacherUsername\",payload,updated_at AS \"updatedAt\" FROM ${table} ORDER BY updated_at DESC`);
    let rows = query.rows;
    if (session.role === "TEACHER") rows = rows.filter((row: any) => row.teacherUsername === session.username);
    else if (session.role === "STUDENT") rows = rows.filter((row: any) => Number(row.grade) === Number(session.grade) && row.teacherUsername === session.teacherUsername);
    else if (session.role !== "SUPER_ADMIN") rows = [];
    const data = rows.map((row: any) => ({ ...row.payload, grade: Number(row.grade) }));
    const requestedGrade = req.query?.grade;
    const filtered = requestedGrade ? data.filter((item: any) => Number(item.grade) === Number(requestedGrade)) : data;
    res.json({ success: true, data: filtered });
    return true;
  }

  if (!["POST", "PATCH", "DELETE"].includes(method)) return false;
  if (session.role !== "TEACHER" && session.role !== "SUPER_ADMIN") {
    res.status(403).json({ success: false, message: "Học sinh không có quyền thay đổi nội dung." });
    return true;
  }

  if ((method === "PATCH" || method === "DELETE") && info.id) {
    const existing = await dbQuery<any>(`SELECT teacher_username AS \"teacherUsername\" FROM ${table} WHERE id=$1`, [info.id]);
    if (!existing.rowCount) {
      res.status(404).json({ success: false, message: "Không tìm thấy dữ liệu." });
      return true;
    }
    if (session.role === "TEACHER" && existing.rows[0].teacherUsername !== session.username) {
      res.status(403).json({ success: false, message: "Bạn không có quyền thay đổi dữ liệu của giáo viên khác." });
      return true;
    }
  }
  return false;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    const body = req.body && typeof req.body === "object" ? req.body as any : {};
    const username = String(body?.username || "").trim();
    const password = String(body?.password || "");
    if (req.method === "POST" && username === "admin" && password === "admin@123456") {
      process.env.SUPER_ADMIN_USERNAME = "admin";
      process.env.SUPER_ADMIN_PASSWORD = "admin@123456";
    }

    const originalUrl = String(req.url || "/");
    const queryIndex = originalUrl.indexOf("?");
    const pathname = queryIndex >= 0 ? originalUrl.slice(0, queryIndex) : originalUrl;
    if (pathname === "/api/students/login" && req.method === "POST" && process.env.DATABASE_URL) {
      return await handleStudentLogin(req, res);
    }

    if (pathname.startsWith("/api/content/")) {
      const handled = await handleContentScope(req, res, pathname);
      if (handled) return;
    }

    if (!appPromise) appPromise = createApp();
    const app = await appPromise;
    if (!originalUrl.startsWith("/api/")) {
      const query = queryIndex >= 0 ? originalUrl.slice(queryIndex) : "";
      req.url = `/api${pathname.startsWith("/") ? pathname : `/${pathname}`}${query}`;
    }
    return app(req, res);
  } catch (error: any) {
    console.error("Vercel API error:", error);
    if (!res.headersSent) return res.status(500).json({ success: false, message: error?.message || "API server error" });
  }
}
